### ISSUE TITLE
What tool did you use to draw graphs?

### ISSUE THREAD

**Issue by despagito** [danielbischoff/shared-webpack-config#1]
E.g. the graph in wiki.
It looks like it's made by graphviz, if so, how do you add labels on edges?

![](https://github.com/danielbischoff/shared-webpack-config/raw/master/basic_idea.svg?sanitize=true)

**Comment by danielbischoff** [comment]
I used https://www.draw.io/
Just double click an arrow and you can edit and also move the label. :)
